### ISSUE TITLE
所以ffplayer是啥

### ISSUE THREAD

**Issue by fzlzjerry** [3150601355/VideoWallPaperDemo#1]

**Comment by shirok1** [comment]
ffmpeg的一个组件，Windows版貌似不自带要另外下载

**Comment by FlorenceZh** [comment]
> _No description provided._

ffmpeg播放器的简单实现

**Comment by larryteal** [comment]
‍老师您好，看了您关于windows的分享受益匪浅，我遇到一个窗口置顶的问题请教一下您，我希望设置一个窗口永远置顶并保持，我尝试了 win32 的API函数 SetWindowPos ，它有用但是不太完美，当有多个窗口都是使用SetWindowPos函数设置了 HWND_TOPMOST 时，鼠标点哪个窗口哪个窗口在最上面，系统中也有一部分窗口默认就是置顶的，比如任务栏窗口。我希望通过设置让其中一个指定的窗口保持指定，无论窗口是否获取焦点。微软的一个工具 inspect.exe 就是这样的，但是不晓得怎么实现的，所以请教老师，望老师给些指点或者出一个视频，非常感谢！
